# See http://docs.travis-ci.com/user/languages/csharp/ for details

# TODO: Test against Mono as well, using matrix.include
language: csharp
mono: none
dotnet: 1.1.5
dist: trusty

script:
  - dotnet restore src/NodaTime
  - dotnet restore src/NodaTime.Test
  - dotnet build src/NodaTime -f netstandard1.3
  - dotnet build src/NodaTime.Test -f netcoreapp1.0
  - dotnet run -p src/NodaTime.Test/*.csproj -f netcoreapp1.0 -- --where=cat!=Slow
