# See http://docs.travis-ci.com/user/languages/csharp/ for details

language: csharp
install:
  - curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | sh && source ~/.dnx/dnvm/dnvm.sh && dnvm upgrade

# Explicitly build the two biggest projects separately; just dnx
# test would work, but separating out the build step makes for
# simpler diagnostics. We run the smaller test suites first, to
# give earlier confirmation that they're working at all.
# (NodaTime.Test can time out easily...)
script:
  - dnu restore
  - dnu build src/NodaTime
  - dnu build src/NodaTime.Test
  - dnx -p src/NodaTime.Serialization.Test test
  - dnx -p src/NodaTime.TzdbCompiler.Test test
  - dnx -p src/NodaTime.Test test "--where=cat != Slow && cat != Overflow"
