# See http://docs.travis-ci.com/user/languages/csharp/ for details

# TODO: Test against Mono as well, using matrix.include
language: csharp
mono: none
dotnet: 3.0.100
dist: xenial

script:
  - build/travis.sh
