name: Noda Time
pygments: true

markdown:      redcarpet
markdown_ext:  markdown,mkd,mkdn,md

# The latest released version number and date of release.
latest: 1.3.0
latest_released_on: June 27th 2014
